[package]

name = "unicode"
version = "0.0.1"
authors = ["Kevin Ballard <kevin@sb.org>"]
build = "src/build.rs"

[dependencies.alfred]
git = "https://github.com/kballard/alfred-rs"

[build-dependencies.time]
git = "https://github.com/rust-lang/time"
